In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [27]:
!wget https://jpata.web.cern.ch/jpata/mlpf/test_data/pred_2020_12_11.npz
    

--2020-12-11 13:53:37--  https://jpata.web.cern.ch/jpata/mlpf/test_data/pred_2020_12_11.npz
Resolving jpata.web.cern.ch (jpata.web.cern.ch)... 137.138.31.235, 188.185.87.216, 188.185.90.87, ...
Connecting to jpata.web.cern.ch (jpata.web.cern.ch)|137.138.31.235|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 69632996 (66M)
Saving to: ‘pred_2020_12_11.npz.4’

pred_2020_12_11.npz 100%[===================>]  66,41M  7,39MB/s    in 8,6s    

2020-12-11 13:53:46 (7,71 MB/s) - ‘pred_2020_12_11.npz.4’ saved [69632996/69632996]



In [32]:
fi = np.load("pred_2020_12_11.npz.4")
ygen = fi["ygen"]
ycand = fi["ycand"]
ypred = fi["ypred"]
ypred_raw = fi["ypred_raw"]

In [31]:
list(fi.keys())

['ygen', 'ycand', 'ypred', 'ypred_raw']

In [87]:
print(ygen[0][0][0])
print(ypred[6][0])
print(ypred_raw[0][0])
print(np.unique(ypred[:,:,0], return_counts = True))

1.0
[ 1.         -0.93207151  0.88258475 -0.49298528  0.62524432 -0.77716577
 -0.78627753]
[-6.844067   8.4386835 -3.3277202 -5.2895026  4.996628  -3.5732553]
(array([0., 1., 2., 3., 4., 5.]), array([    22, 352781,  29269, 129511,    146,    271]))


In [58]:
#Classification to binary
#Concatenate matricies
conc_ygen = np.concatenate(ygen[0:100])
conc_ypred= np.concatenate(ypred[0:100])
#extract ids
ygen_ids=conc_ygen[:,0]
ypred_ids=conc_ypred[:,0]



In [69]:
#Check if uniqueness cheks out
print(np.unique(ygen_ids[:], return_counts = True))
print(np.unique(ygen[:, :, 0], return_counts=True))
print(np.unique(ypred_ids[:], return_counts = True))
print(np.unique(ypred[:,:,0], return_counts = True))


(array([0., 1., 2., 3., 4., 5.], dtype=float32), array([ 50421, 313620,  26770, 120023,    900,    266]))
(array([0., 1., 2., 3., 4., 5.], dtype=float32), array([ 50421, 313620,  26770, 120023,    900,    266]))
(array([0., 1., 2., 3., 4., 5.]), array([    22, 352781,  29269, 129511,    146,    271]))
(array([0., 1., 2., 3., 4., 5.]), array([    22, 352781,  29269, 129511,    146,    271]))


In [74]:
#There must be 50421 zeroes and 461579 non_zero values in ygen
#There must be 22 zeroes and 511978
ygen_ids_b=np.where(ygen_ids>0,1,ygen_ids)
ypred_ids_b=np.where(ypred_ids>0,1,ypred_ids)
print(np.unique(ygen_ids_b[:], return_counts = True))
print(np.unique(ypred_ids_b[:], return_counts = True))

(array([0., 1.], dtype=float32), array([ 50421, 461579]))
(array([0., 1.]), array([    22, 511978]))


In [82]:
#Accuracy precentage %

right=0
wrong=0
n_events=len(conc_ygen)#5120*100
for i in range(n_events):
    if ypred_ids_b[i]==ygen_ids_b[i]:
        right += 1
    else:
        wrong += 1
        
print(right)
print(wrong)
print(f'accuracy: {right/n_events}%')


461571
50429
accuracy: 0.901505859375%


In [94]:
#Normalize y_raw with softmax operation
from scipy.special import softmax
test_softmax=softmax(ypred_raw[0][0])
print(test_softmax)
sum(test)
                          

[2.2340883e-07 9.6897906e-01 7.5202106e-06 1.0573985e-06 3.1006204e-02
 5.8829551e-06]


0.9999999485872735

In [93]:
sum(test)

0.9999999485872735